version: '{build}'
branches:
  only:
  - master
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
clone_folder: c:\projects\glbinding
environment:
  matrix:
  - GENERATOR: 'Visual Studio 15 Win64'
  - GENERATOR: 'Visual Studio 14 Win64'
before_build:
- cmd: >-
    mkdir build
    
    cd build
    
    cmake --version

    cmake .. -G "%GENERATOR%"
    
build:
  project: c:\projects\glbinding\build\glbinding.sln
  verbosity: minimal

matrix:
  fast_finish: true
