version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\glbinding
image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013
configuration:
- Release
- Debug
platform:
- x64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set generator=%APPVEYOR_BUILD_WORKER_IMAGE% Win64
- echo "%generator%"

before_build:
- cmd: >-
    mkdir build
    
    cd build
    
    cmake --version

    cmake .. -G "%generator%"
    
build:
  project: c:\projects\glbinding\build\glbinding.sln
  verbosity: minimal
  parallel: true 
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - sources/
