version: {build}
image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013
configuration:
- Release
- Debug
platform: x64
clone_folder: c:\projects\glbinding
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake ..
build:
  project: c:\projects\glbinding\build\glbinding.sln
  verbosity: minimal
