version: 1.0.{build}

branches:
  except:
  - gh-pages

image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013

clone_folder: c:\projects\myproject

configuration:
- Release
- Debug

platform: x64

before_build:
- cmd:
  - mkdir build
  - cd build
  - cmake ..

build:
  project: build/glbinding.sln
  verbosity: minimal
