version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\glbinding
image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013
configuration:
- Release
- Debug
platform:
- x64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- if '%APPVEYOR_BUILD_WORKER_IMAGE%'=='Visual Studio 2017' ( set generator='Visual Studio 15 Win64' )
- if '%APPVEYOR_BUILD_WORKER_IMAGE%'=='Visual Studio 2015' ( set generator='Visual Studio 14 Win64' )
- if '%APPVEYOR_BUILD_WORKER_IMAGE%'=='Visual Studio 2013' ( set generator='Visual Studio 12 Win64' )

before_build:
- cmd: >-
    mkdir build
    
    cd build
    
    cmake --version

    cmake .. -G %generator%
    
build:
  project: c:\projects\glbinding\build\glbinding.sln
  verbosity: minimal
  parallel: true 
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - sources/
